version: "3.9"
services:
  jenkins-blueocean:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

volumes:
  jenkins-data: {}
  jenkins-docker-certs: {}

networks:
  jenkins: {}

